version: "3.9"
services:
  app:
    build: .
    image: jooby-example:0.0.2
    ports:
      - "8080:8080"
    environment:
      # you can add JVM opts or app-specific env here
      - JAVA_TOOL_OPTIONS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    healthcheck:
      test: ["CMD", "bash", "-lc", "exec 3<>/dev/tcp/127.0.0.1/7070 && echo -e 'GET /javalin/api/ HTTP/1.1\r\nHost: localhost\r\n\r\n' >&3 && sleep 1 && head -n1 <&3 | grep -q 'HTTP/'"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
